# Prologue

- The RMS Titanic set sail on its maiden voyage in 1912, crossing the Atlantic from Southampton, England to New York City.
- The ship never completed the voyage, sinking to the bottom of the Atlantic Ocean after hitting an iceberg, bringing down 1,502 of 2,224 passengers onboard.
- The data we will be using for training our model is provided by Kaggle.

# Importing Libraries

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# Dataset

In [14]:
df = pd.read_csv('passengers.csv')

In [15]:
df.shape

(891, 12)

In [16]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

## Data Cleaning

In [ ]:
data_frame(['column']).map({'initial_value_1':'updated_value_1','initial_value_2':'updated_value_2'})

In [17]:
df['Sex'] = df['Sex'].map({ 'male': 0, 'female': 1 })

In [20]:
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [22]:
df['Age'].fillna(value = np.mean(df['Age']), inplace = True)

In [23]:
df['Age']

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...    
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age, Length: 891, dtype: float64

In [25]:
df['First Class'] = df['Pclass'].apply(lambda x: 1 if x == 1 else 0)

In [27]:
df['Second Class'] = df['Pclass'].apply(lambda x: 1 if x == 2 else 0)

In [28]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare Cabin Embarked  First Class  Second Class  
0         A/5 21171   7.2500   NaN        S            0             0  
1          PC 17599  71.2833   C85        C            1             0  
2  STON/O2. 3101282   7.9250   NaN        S            0             0  
3            113803  53.1000  C123        S            1             0  
4            373450   8.0500   NaN        S            0             0

In [29]:
df.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

     Sex        Age  SibSp  Parch      Ticket   Fare Cabin Embarked  \
886    0  27.000000      0      0      211536  13.00   NaN        S   
887    1  19.000000      0      0      112053  30.00   B42        S   
888    1  29.699118      1      2  W./C. 6607  23.45   NaN        S   
889    0  26.000000      0      0      111369  30.00  C148        C   
890    0  32.000000      0      0      370376   7.75   NaN        Q   

     First Class  Second Class  
886            0             1  
887            1             0  
888            0             0  
889            1             0  
890            0             0

# Feature Selection

In [31]:
Features = df[['Sex', 'Age', 'First Class', 'Second Class']]

In [34]:
Survival = df[['Survived']]

In [36]:
Features.head()

Sex   Age  First Class  Second Class
0    0  22.0            0             0
1    1  38.0            1             0
2    1  26.0            0             0
3    1  35.0            1             0
4    0  35.0            0             0

In [37]:
Survival.head()

Survived
0         0
1         1
2         1
3         1
4         0

# Splitting Data

In [41]:
X_train, X_test, y_train, y_test = train_test_split(Features, Survival, test_size = 0.2, random_state = 0)

In [42]:
X_train.shape

(712, 4)

In [47]:
X_train.head()

Sex        Age  First Class  Second Class
140    1  29.699118            0             0
439    0  31.000000            0             1
817    0  31.000000            0             1
378    0  20.000000            0             0
491    0  21.000000            0             0

In [45]:
y_train.shape

(712, 1)

In [48]:
y_train.head()

Survived
140         0
439         0
817         0
378         0
491         0

In [44]:
X_test.shape

(179, 4)

In [49]:
X_test.head()

Sex        Age  First Class  Second Class
495    0  29.699118            0             0
648    0  29.699118            0             0
278    0   7.000000            0             0
31     1  29.699118            1             0
255    1  29.000000            0             0

In [46]:
X_test.shape

(179, 4)

In [50]:
X_test.head()

Sex        Age  First Class  Second Class
495    0  29.699118            0             0
648    0  29.699118            0             0
278    0   7.000000            0             0
31     1  29.699118            1             0
255    1  29.000000            0             0

In [51]:
y_test.shape

(179, 1)

In [52]:
y_test.head()

Survived
495         0
648         0
278         0
31          1
255         1

# Normalizing

In [53]:
Scaler = StandardScaler()

In [54]:
X_train = Scaler.fit_transform(X_train)

In [55]:
X_test = Scaler.transform(X_test)

# Training A Logistic Regressor

In [56]:
LogisticRegressor = LogisticRegression()

In [63]:
LogisticRegressor.fit(X_train, y_train)

c:\users\muham\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

# Evaluation

In [66]:
LogisticRegressor.score(X_test, y_test)

0.7988826815642458

In [69]:
LogisticRegressor.coef_

array([[ 1.20797072, -0.46188153,  0.91609258,  0.45550712]])

In [68]:
print(list(zip(['Sex', 'Age', 'FirstClass', 'SecondClass'], LogisticRegressor.coef_[0])))

[('Sex', 1.2079707219642437), ('Age', -0.4618815268777891), ('FirstClass', 0.9160925848253088), ('SecondClass', 0.45550712381193714)]


# Making Prediction

In [70]:
# :D :D :D
Jack = np.array([0.0, 20.0, 0.0, 0.0])
Rose = np.array([1.0, 17.0, 1.0, 0.0])

In [73]:
JackAndRose = np.array([Jack, Rose])

In [75]:
NormalizedJackAndRose = Scaler.transform(JackAndRose)

In [76]:
LogisticRegressor.predict(NormalizedJackAndRose)

array([0, 1], dtype=int64)

In [77]:
LogisticRegressor.predict_proba(NormalizedJackAndRose)

array([[0.8721684 , 0.1278316 ],
       [0.05354073, 0.94645927]])

# Epilogue

- It Worked! Rose has survived but Jack has drowned :(